apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
       variant: prod

resources:
  - ../../base


patches:
  - path: deployment_patch.yaml
  - path: service_patch.yaml
  - path: ingress_patch.yaml

namePrefix: prod-
  