apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
       variant: dev

resources:
  - ../../base


patches:
  - path: replicas_patch.yaml
  - path: service_patch.yaml

namePrefix: dev-
  